trigger: 
- main

resources:
  repositories:
    - repository: configRepo
      type: github
      ref: main
      endpoint: mvankrieken
      name: mvankrieken/argocd-config

pool: 
  name: Local-kubernetes
  demands: 
    - DEF_TYPE -equals build

workspace:
  clean: all 

steps:
 # Checkouts main code
 - checkout: self

 # Build image
 - bash: 
    echo "##vso[task.setvariable variable=GIT_SHORT_ID]$(echo $(Build.SourceVersion) | cut -c1-7)"
    
 - task: Docker@2
   displayName: Build agent image
   inputs:
     repository: 'local/az-local-agent-customer'
     command: build
     Dockerfile: local-kubernetes-azure-agent-customer/image/azure-agent.dockerfile
     buildContext: local-kubernetes-azure-agent-customer/image
     tags: $(GIT_SHORT_ID)
     arguments: '--platform linux/x86_64'

 # Checkout config
 - checkout: configRepo
   clean: true
   persistCredentials: true

 # Update deployment file
 - script: |
    cd argocd-config/
    git config --global user.name "Martin van Krieken"
    git config --global user.email "mkrieken@gmail.com"
    git fetch
    git branch -v -a
    git checkout -b main
    git branch -v -a
    yq eval -i '.image.tag = "$(GIT_SHORT_ID)"' azure-customer-agent/values.yaml
    git add .
    git commit -m "New version for azure-customer-agent/values.yaml"
    git push origin main